
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package Analizador;

/** CUP generated class containing symbol constants. */
public class Simbolos {
  /* terminals */
  public static final int id = 2;
  public static final int coma = 3;
  public static final int cadena = 8;
  public static final int prFin = 5;
  public static final int prInicio = 4;
  public static final int EOF = 0;
  public static final int caracter = 7;
  public static final int numero = 6;
  public static final int error = 1;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "id",
  "coma",
  "prInicio",
  "prFin",
  "numero",
  "caracter",
  "cadena"
  };
}

