
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package Analizador;

/** CUP generated class containing symbol constants. */
public class Tokens {
  /* terminals */
  public static final int thasta = 23;
  public static final int Entero = 53;
  public static final int tigual = 64;
  public static final int tFinFuncion = 35;
  public static final int Todo_Valores = 58;
  public static final int tosi = 17;
  public static final int tor = 67;
  public static final int tfinsegun = 21;
  public static final int tmenigual = 63;
  public static final int coma = 57;
  public static final int treturn = 30;
  public static final int tpot = 44;
  public static final int tconparametros = 33;
  public static final int Valida_Pot = 59;
  public static final int corfin = 5;
  public static final int Tinteg = 20;
  public static final int tcomo = 9;
  public static final int tmenor = 61;
  public static final int tMayigual = 62;
  public static final int tTipoDato = 56;
  public static final int tingreso = 8;
  public static final int Valida_SC = 70;
  public static final int corini = 4;
  public static final int tejecutar = 36;
  public static final int parefin = 3;
  public static final int tSi = 13;
  public static final int tfin = 7;
  public static final int tmayor = 60;
  public static final int tnot = 68;
  public static final int tand = 66;
  public static final int pareini = 2;
  public static final int tdistinto = 65;
  public static final int EOF = 0;
  public static final int tdiv = 42;
  public static final int error = 1;
  public static final int timprimir = 37;
  public static final int Valida_CC = 46;
  public static final int tsegun = 18;
  public static final int tconValor = 10;
  public static final int tinicio = 6;
  public static final int thacer = 19;
  public static final int tasignacion = 12;
  public static final int trest = 40;
  public static final int tentonces = 15;
  public static final int car_NaL = 50;
  public static final int trepit = 28;
  public static final int tmul = 43;
  public static final int tfinsi = 14;
  public static final int tfuncion = 34;
  public static final int tmod = 45;
  public static final int tmasmas = 25;
  public static final int variable = 55;
  public static final int boolV = 51;
  public static final int tcon = 69;
  public static final int tpara = 22;
  public static final int tmientras = 26;
  public static final int tpuntoComa = 11;
  public static final int car_LaN = 49;
  public static final int tFinMi = 27;
  public static final int comentario = 47;
  public static final int tFinpara = 24;
  public static final int tmetodo = 31;
  public static final int Decimal = 54;
  public static final int tFINMetodo = 32;
  public static final int thastaque = 29;
  public static final int boolF = 52;
  public static final int tDLcontrario = 16;
  public static final int exp = 39;
  public static final int tsum = 41;
  public static final int timprimirNL = 38;
  public static final int cadena = 48;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "pareini",
  "parefin",
  "corini",
  "corfin",
  "tinicio",
  "tfin",
  "tingreso",
  "tcomo",
  "tconValor",
  "tpuntoComa",
  "tasignacion",
  "tSi",
  "tfinsi",
  "tentonces",
  "tDLcontrario",
  "tosi",
  "tsegun",
  "thacer",
  "Tinteg",
  "tfinsegun",
  "tpara",
  "thasta",
  "tFinpara",
  "tmasmas",
  "tmientras",
  "tFinMi",
  "trepit",
  "thastaque",
  "treturn",
  "tmetodo",
  "tFINMetodo",
  "tconparametros",
  "tfuncion",
  "tFinFuncion",
  "tejecutar",
  "timprimir",
  "timprimirNL",
  "exp",
  "trest",
  "tsum",
  "tdiv",
  "tmul",
  "tpot",
  "tmod",
  "Valida_CC",
  "comentario",
  "cadena",
  "car_LaN",
  "car_NaL",
  "boolV",
  "boolF",
  "Entero",
  "Decimal",
  "variable",
  "tTipoDato",
  "coma",
  "Todo_Valores",
  "Valida_Pot",
  "tmayor",
  "tmenor",
  "tMayigual",
  "tmenigual",
  "tigual",
  "tdistinto",
  "tand",
  "tor",
  "tnot",
  "tcon",
  "Valida_SC"
  };
}

